FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

# we need to install system dependencies.
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# to copy full project code 

COPY . . 

CMD [ "gunicorn","ecommerce.wsgi:application", "--bind", "0.0.0.0:8000" ]
