# Generated by Django 5.2.7 on 2025-10-29 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='id_default',
            new_name='is_default',
        ),
    ]
