# Generated by Django 5.2.7 on 2025-11-03 15:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_rename_id_default_address_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
