# Generated by Django 5.2.7 on 2025-11-29 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_address_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
